// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

/// {@template assets_generator.assets_images_20_enemies_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/20 Enemies.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_blue_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Blue.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_brown_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Brown.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_gray_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Gray.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_green_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Green.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_pink_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Pink.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_purple_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Purple.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_background_yellow_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Background/Yellow.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_hud_joystick_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/HUD/Joystick.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_hud_jumpbutton_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/HUD/JumpButton.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_hud_knob_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/HUD/Knob.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_hello_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Hello.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box1_break_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box1/Break.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box1_hit_28x24_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box1/Hit 28x24.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box1_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box1/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box2_break_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box2/Break.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box2_hit_28x24_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box2/Hit 28x24.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box2_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box2/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box3_break_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box3/Break.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box3_hit_28x24_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box3/Hit 28x24.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_boxes_box3_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Boxes/Box3/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_flag_idle64x64_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/Checkpoint/Checkpoint Flag Idle64x64.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_flag_out_64x64_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/Checkpoint/Checkpoint Flag Out 64x64.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_no_flag_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/Checkpoint/Checkpoint No Flag.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_end_end_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/End/End Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_end_end_pressed_64x64_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/End/End Pressed 64x64.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_start_start_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/Start/Start Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_checkpoints_start_start_moving_64x64_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Checkpoints/Start/Start Moving 64x64.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_apple_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Apple.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_bananas_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Bananas.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_cherries_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Cherries.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_collected_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Collected.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_kiwi_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Kiwi.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_melon_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Melon.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_orange_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Orange.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_pineapple_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Pineapple.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_items_fruits_strawberry_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Items/Fruits/Strawberry.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_appearing_96x96_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Appearing 96x96.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_desappearing_96x96_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Desappearing 96x96.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_double_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Double Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_fall_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Fall 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_hit_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Hit 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_idle_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Idle 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_run_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Run 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_mask_dude_wall_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Mask Dude/Wall Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_double_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Double Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_fall_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Fall 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_hit_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Hit 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_idle_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Idle 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_run_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Run 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_ninja_frog_wall_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Ninja Frog/Wall Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_double_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Double Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_fall_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Fall 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_hit_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Hit 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_idle_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Idle 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_run_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Run 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_pink_man_wall_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Pink Man/Wall Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_double_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Double Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_fall_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Fall 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_hit_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Hit 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_idle_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Idle 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_run_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Run 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_main_characters_virtual_guy_wall_jump_32x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Main Characters/Virtual Guy/Wall Jump 32x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_achievements_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Achievements.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_back_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Back.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_close_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Close.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_leaderboard_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Leaderboard.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_levels_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Levels.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_next_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Next.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_play_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Play.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_previous_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Previous.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_restart_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Restart.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_settings_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Settings.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_buttons_volume_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Buttons/Volume.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_01_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/01.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_02_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/02.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_03_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/03.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_04_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/04.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_05_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/05.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_06_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/06.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_07_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/07.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_08_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/08.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_09_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/09.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_10_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/10.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_11_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/11.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_12_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/12.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_13_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/13.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_14_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/14.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_15_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/15.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_16_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/16.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_17_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/17.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_18_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/18.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_19_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/19.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_20_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/20.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_21_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/21.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_22_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/22.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_23_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/23.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_24_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/24.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_25_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/25.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_26_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/26.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_27_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/27.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_28_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/28.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_29_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/29.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_30_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/30.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_31_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/31.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_33_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/33.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_34_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/34.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_35_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/35.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_36_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/36.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_37_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/37.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_38_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/38.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_39_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/39.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_40_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/40.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_41_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/41.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_43_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/43.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_44_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/44.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_45_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/45.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_46_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/46.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_47_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/47.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_48_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/48.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_49_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/49.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_levels_50_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Levels/50.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_text_text_black_8x10_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Text/Text Black 8x10.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_menu_text_text_white_8x10_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Menu/Text/Text White 8x10.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_other_confetti_16x16_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Other/Confetti 16x16.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_other_dust_particle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Other/Dust Particle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_other_shadow_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Other/Shadow.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_other_transition_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Other/Transition.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_terrain_terrain_16x16_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Terrain/Terrain 16x16.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_arrow_hit_18x18_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Arrow/Hit 18x18.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_arrow_idle_18x18_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Arrow/Idle 18x18.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_blocks_hitside_22x22_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Blocks/HitSide 22x22.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_blocks_hittop_22x22_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Blocks/HitTop 22x22.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_blocks_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Blocks/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_blocks_part_1_22x22_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Blocks/Part 1 22x22.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_blocks_part_2_22x22_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Blocks/Part 2 22x22.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_falling_platforms_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Falling Platforms/Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_falling_platforms_on_32x10_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Falling Platforms/On 32x10.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_fan_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Fan/Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_fan_on_24x8_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Fan/On 24x8.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_fire_hit_16x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Fire/Hit 16x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_fire_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Fire/Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_fire_on_16x32_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Fire/On 16x32.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_platforms_brown_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Platforms/Brown Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_platforms_brown_on_32x8_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Platforms/Brown On 32x8.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_platforms_chain_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Platforms/Chain.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_platforms_grey_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Platforms/Grey Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_platforms_grey_on_32x8_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Platforms/Grey On 32x8.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_blink_42x42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Blink 42x42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_bottom_hit_42x42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Bottom Hit 42x42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_left_hit_42x42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Left Hit 42x42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_right_hit_42x42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Right Hit 42x42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_rock_head_top_hit_42x42_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Rock Head/Top Hit 42x42.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_sand_mud_ice_ice_particle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Sand Mud Ice/Ice Particle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_sand_mud_ice_mud_particle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Sand Mud Ice/Mud Particle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_sand_mud_ice_sand_mud_ice_16x6_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Sand Mud Ice/Sand Mud Ice 16x6.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_sand_mud_ice_sand_particle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Sand Mud Ice/Sand Particle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_saw_chain_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Saw/Chain.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_saw_off_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Saw/Off.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_saw_on_38x38_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Saw/On 38x38.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_blink_54x52_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Blink 54x52.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_bottom_hit_54x52_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Bottom Hit 54x52.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_left_hit_54x52_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Left Hit 54x52.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_right_hit_54x52_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Right Hit 54x52.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spike_head_top_hit_54x52_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spike Head/Top Hit 54x52.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spiked_ball_chain_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spiked Ball/Chain.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spiked_ball_spiked_ball_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spiked Ball/Spiked Ball.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_spikes_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Spikes/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_trampoline_idle_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Trampoline/Idle.png)
/// {@endtemplate}

/// {@template assets_generator.assets_images_traps_trampoline_jump_28x28_png.preview}
/// ![](c:\users\usuario\projetos\pixel_adventure\assets/images/Traps/Trampoline/Jump 28x28.png)
/// {@endtemplate}

// ignore_for_file: camel_case_types, unused_element
class _ {}