// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/assets_generator
// **************************************************************************
// ignore_for_file: constant_identifier_names

class Assets {
  const Assets._();

  /// {@macro assets_generator.assets_images_20_enemies_png.preview}
  static const String assets_images_20_enemies_png =
      'assets/images/20 Enemies.png';

  /// {@macro assets_generator.assets_images_background_blue_png.preview}
  static const String assets_images_background_blue_png =
      'assets/images/Background/Blue.png';

  /// {@macro assets_generator.assets_images_background_brown_png.preview}
  static const String assets_images_background_brown_png =
      'assets/images/Background/Brown.png';

  /// {@macro assets_generator.assets_images_background_gray_png.preview}
  static const String assets_images_background_gray_png =
      'assets/images/Background/Gray.png';

  /// {@macro assets_generator.assets_images_background_green_png.preview}
  static const String assets_images_background_green_png =
      'assets/images/Background/Green.png';

  /// {@macro assets_generator.assets_images_background_pink_png.preview}
  static const String assets_images_background_pink_png =
      'assets/images/Background/Pink.png';

  /// {@macro assets_generator.assets_images_background_purple_png.preview}
  static const String assets_images_background_purple_png =
      'assets/images/Background/Purple.png';

  /// {@macro assets_generator.assets_images_background_yellow_png.preview}
  static const String assets_images_background_yellow_png =
      'assets/images/Background/Yellow.png';

  /// {@macro assets_generator.assets_images_hud_joystick_png.preview}
  static const String assets_images_hud_joystick_png =
      'assets/images/HUD/Joystick.png';

  /// {@macro assets_generator.assets_images_hud_jumpbutton_png.preview}
  static const String assets_images_hud_jumpbutton_png =
      'assets/images/HUD/JumpButton.png';

  /// {@macro assets_generator.assets_images_hud_knob_png.preview}
  static const String assets_images_hud_knob_png = 'assets/images/HUD/Knob.png';

  /// {@macro assets_generator.assets_images_hello_png.preview}
  static const String assets_images_hello_png = 'assets/images/Hello.png';

  /// {@macro assets_generator.assets_images_items_boxes_box1_break_png.preview}
  static const String assets_images_items_boxes_box1_break_png =
      'assets/images/Items/Boxes/Box1/Break.png';

  /// {@macro assets_generator.assets_images_items_boxes_box1_hit_28x24_png.preview}
  static const String assets_images_items_boxes_box1_hit_28x24_png =
      'assets/images/Items/Boxes/Box1/Hit 28x24.png';

  /// {@macro assets_generator.assets_images_items_boxes_box1_idle_png.preview}
  static const String assets_images_items_boxes_box1_idle_png =
      'assets/images/Items/Boxes/Box1/Idle.png';

  /// {@macro assets_generator.assets_images_items_boxes_box2_break_png.preview}
  static const String assets_images_items_boxes_box2_break_png =
      'assets/images/Items/Boxes/Box2/Break.png';

  /// {@macro assets_generator.assets_images_items_boxes_box2_hit_28x24_png.preview}
  static const String assets_images_items_boxes_box2_hit_28x24_png =
      'assets/images/Items/Boxes/Box2/Hit 28x24.png';

  /// {@macro assets_generator.assets_images_items_boxes_box2_idle_png.preview}
  static const String assets_images_items_boxes_box2_idle_png =
      'assets/images/Items/Boxes/Box2/Idle.png';

  /// {@macro assets_generator.assets_images_items_boxes_box3_break_png.preview}
  static const String assets_images_items_boxes_box3_break_png =
      'assets/images/Items/Boxes/Box3/Break.png';

  /// {@macro assets_generator.assets_images_items_boxes_box3_hit_28x24_png.preview}
  static const String assets_images_items_boxes_box3_hit_28x24_png =
      'assets/images/Items/Boxes/Box3/Hit 28x24.png';

  /// {@macro assets_generator.assets_images_items_boxes_box3_idle_png.preview}
  static const String assets_images_items_boxes_box3_idle_png =
      'assets/images/Items/Boxes/Box3/Idle.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_flag_idle64x64_png.preview}
  static const String
      assets_images_items_checkpoints_checkpoint_checkpoint_flag_idle64x64_png =
      'assets/images/Items/Checkpoints/Checkpoint/Checkpoint Flag Idle64x64.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_flag_out_64x64_png.preview}
  static const String
      assets_images_items_checkpoints_checkpoint_checkpoint_flag_out_64x64_png =
      'assets/images/Items/Checkpoints/Checkpoint/Checkpoint Flag Out 64x64.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_checkpoint_checkpoint_no_flag_png.preview}
  static const String
      assets_images_items_checkpoints_checkpoint_checkpoint_no_flag_png =
      'assets/images/Items/Checkpoints/Checkpoint/Checkpoint No Flag.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_end_end_idle_png.preview}
  static const String assets_images_items_checkpoints_end_end_idle_png =
      'assets/images/Items/Checkpoints/End/End Idle.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_end_end_pressed_64x64_png.preview}
  static const String
      assets_images_items_checkpoints_end_end_pressed_64x64_png =
      'assets/images/Items/Checkpoints/End/End Pressed 64x64.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_start_start_idle_png.preview}
  static const String assets_images_items_checkpoints_start_start_idle_png =
      'assets/images/Items/Checkpoints/Start/Start Idle.png';

  /// {@macro assets_generator.assets_images_items_checkpoints_start_start_moving_64x64_png.preview}
  static const String
      assets_images_items_checkpoints_start_start_moving_64x64_png =
      'assets/images/Items/Checkpoints/Start/Start Moving 64x64.png';

  /// {@macro assets_generator.assets_images_items_fruits_apple_png.preview}
  static const String assets_images_items_fruits_apple_png =
      'assets/images/Items/Fruits/Apple.png';

  /// {@macro assets_generator.assets_images_items_fruits_bananas_png.preview}
  static const String assets_images_items_fruits_bananas_png =
      'assets/images/Items/Fruits/Bananas.png';

  /// {@macro assets_generator.assets_images_items_fruits_cherries_png.preview}
  static const String assets_images_items_fruits_cherries_png =
      'assets/images/Items/Fruits/Cherries.png';

  /// {@macro assets_generator.assets_images_items_fruits_collected_png.preview}
  static const String assets_images_items_fruits_collected_png =
      'assets/images/Items/Fruits/Collected.png';

  /// {@macro assets_generator.assets_images_items_fruits_kiwi_png.preview}
  static const String assets_images_items_fruits_kiwi_png =
      'assets/images/Items/Fruits/Kiwi.png';

  /// {@macro assets_generator.assets_images_items_fruits_melon_png.preview}
  static const String assets_images_items_fruits_melon_png =
      'assets/images/Items/Fruits/Melon.png';

  /// {@macro assets_generator.assets_images_items_fruits_orange_png.preview}
  static const String assets_images_items_fruits_orange_png =
      'assets/images/Items/Fruits/Orange.png';

  /// {@macro assets_generator.assets_images_items_fruits_pineapple_png.preview}
  static const String assets_images_items_fruits_pineapple_png =
      'assets/images/Items/Fruits/Pineapple.png';

  /// {@macro assets_generator.assets_images_items_fruits_strawberry_png.preview}
  static const String assets_images_items_fruits_strawberry_png =
      'assets/images/Items/Fruits/Strawberry.png';

  /// {@macro assets_generator.assets_images_main_characters_appearing_96x96_png.preview}
  static const String assets_images_main_characters_appearing_96x96_png =
      'assets/images/Main Characters/Appearing 96x96.png';

  /// {@macro assets_generator.assets_images_main_characters_desappearing_96x96_png.preview}
  static const String assets_images_main_characters_desappearing_96x96_png =
      'assets/images/Main Characters/Desappearing 96x96.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_double_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_mask_dude_double_jump_32x32_png =
      'assets/images/Main Characters/Mask Dude/Double Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_fall_32x32_png.preview}
  static const String assets_images_main_characters_mask_dude_fall_32x32_png =
      'assets/images/Main Characters/Mask Dude/Fall 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_hit_32x32_png.preview}
  static const String assets_images_main_characters_mask_dude_hit_32x32_png =
      'assets/images/Main Characters/Mask Dude/Hit 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_idle_32x32_png.preview}
  static const String assets_images_main_characters_mask_dude_idle_32x32_png =
      'assets/images/Main Characters/Mask Dude/Idle 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_jump_32x32_png.preview}
  static const String assets_images_main_characters_mask_dude_jump_32x32_png =
      'assets/images/Main Characters/Mask Dude/Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_run_32x32_png.preview}
  static const String assets_images_main_characters_mask_dude_run_32x32_png =
      'assets/images/Main Characters/Mask Dude/Run 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_mask_dude_wall_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_mask_dude_wall_jump_32x32_png =
      'assets/images/Main Characters/Mask Dude/Wall Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_double_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_ninja_frog_double_jump_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Double Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_fall_32x32_png.preview}
  static const String assets_images_main_characters_ninja_frog_fall_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Fall 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_hit_32x32_png.preview}
  static const String assets_images_main_characters_ninja_frog_hit_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Hit 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_idle_32x32_png.preview}
  static const String assets_images_main_characters_ninja_frog_idle_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Idle 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_jump_32x32_png.preview}
  static const String assets_images_main_characters_ninja_frog_jump_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_run_32x32_png.preview}
  static const String assets_images_main_characters_ninja_frog_run_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Run 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_ninja_frog_wall_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_ninja_frog_wall_jump_32x32_png =
      'assets/images/Main Characters/Ninja Frog/Wall Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_double_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_pink_man_double_jump_32x32_png =
      'assets/images/Main Characters/Pink Man/Double Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_fall_32x32_png.preview}
  static const String assets_images_main_characters_pink_man_fall_32x32_png =
      'assets/images/Main Characters/Pink Man/Fall 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_hit_32x32_png.preview}
  static const String assets_images_main_characters_pink_man_hit_32x32_png =
      'assets/images/Main Characters/Pink Man/Hit 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_idle_32x32_png.preview}
  static const String assets_images_main_characters_pink_man_idle_32x32_png =
      'assets/images/Main Characters/Pink Man/Idle 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_jump_32x32_png.preview}
  static const String assets_images_main_characters_pink_man_jump_32x32_png =
      'assets/images/Main Characters/Pink Man/Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_run_32x32_png.preview}
  static const String assets_images_main_characters_pink_man_run_32x32_png =
      'assets/images/Main Characters/Pink Man/Run 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_pink_man_wall_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_pink_man_wall_jump_32x32_png =
      'assets/images/Main Characters/Pink Man/Wall Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_double_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_virtual_guy_double_jump_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Double Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_fall_32x32_png.preview}
  static const String assets_images_main_characters_virtual_guy_fall_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Fall 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_hit_32x32_png.preview}
  static const String assets_images_main_characters_virtual_guy_hit_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Hit 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_idle_32x32_png.preview}
  static const String assets_images_main_characters_virtual_guy_idle_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Idle 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_jump_32x32_png.preview}
  static const String assets_images_main_characters_virtual_guy_jump_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Jump 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_run_32x32_png.preview}
  static const String assets_images_main_characters_virtual_guy_run_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Run 32x32.png';

  /// {@macro assets_generator.assets_images_main_characters_virtual_guy_wall_jump_32x32_png.preview}
  static const String
      assets_images_main_characters_virtual_guy_wall_jump_32x32_png =
      'assets/images/Main Characters/Virtual Guy/Wall Jump 32x32.png';

  /// {@macro assets_generator.assets_images_menu_buttons_achievements_png.preview}
  static const String assets_images_menu_buttons_achievements_png =
      'assets/images/Menu/Buttons/Achievements.png';

  /// {@macro assets_generator.assets_images_menu_buttons_back_png.preview}
  static const String assets_images_menu_buttons_back_png =
      'assets/images/Menu/Buttons/Back.png';

  /// {@macro assets_generator.assets_images_menu_buttons_close_png.preview}
  static const String assets_images_menu_buttons_close_png =
      'assets/images/Menu/Buttons/Close.png';

  /// {@macro assets_generator.assets_images_menu_buttons_leaderboard_png.preview}
  static const String assets_images_menu_buttons_leaderboard_png =
      'assets/images/Menu/Buttons/Leaderboard.png';

  /// {@macro assets_generator.assets_images_menu_buttons_levels_png.preview}
  static const String assets_images_menu_buttons_levels_png =
      'assets/images/Menu/Buttons/Levels.png';

  /// {@macro assets_generator.assets_images_menu_buttons_next_png.preview}
  static const String assets_images_menu_buttons_next_png =
      'assets/images/Menu/Buttons/Next.png';

  /// {@macro assets_generator.assets_images_menu_buttons_play_png.preview}
  static const String assets_images_menu_buttons_play_png =
      'assets/images/Menu/Buttons/Play.png';

  /// {@macro assets_generator.assets_images_menu_buttons_previous_png.preview}
  static const String assets_images_menu_buttons_previous_png =
      'assets/images/Menu/Buttons/Previous.png';

  /// {@macro assets_generator.assets_images_menu_buttons_restart_png.preview}
  static const String assets_images_menu_buttons_restart_png =
      'assets/images/Menu/Buttons/Restart.png';

  /// {@macro assets_generator.assets_images_menu_buttons_settings_png.preview}
  static const String assets_images_menu_buttons_settings_png =
      'assets/images/Menu/Buttons/Settings.png';

  /// {@macro assets_generator.assets_images_menu_buttons_volume_png.preview}
  static const String assets_images_menu_buttons_volume_png =
      'assets/images/Menu/Buttons/Volume.png';

  /// {@macro assets_generator.assets_images_menu_levels_01_png.preview}
  static const String assets_images_menu_levels_01_png =
      'assets/images/Menu/Levels/01.png';

  /// {@macro assets_generator.assets_images_menu_levels_02_png.preview}
  static const String assets_images_menu_levels_02_png =
      'assets/images/Menu/Levels/02.png';

  /// {@macro assets_generator.assets_images_menu_levels_03_png.preview}
  static const String assets_images_menu_levels_03_png =
      'assets/images/Menu/Levels/03.png';

  /// {@macro assets_generator.assets_images_menu_levels_04_png.preview}
  static const String assets_images_menu_levels_04_png =
      'assets/images/Menu/Levels/04.png';

  /// {@macro assets_generator.assets_images_menu_levels_05_png.preview}
  static const String assets_images_menu_levels_05_png =
      'assets/images/Menu/Levels/05.png';

  /// {@macro assets_generator.assets_images_menu_levels_06_png.preview}
  static const String assets_images_menu_levels_06_png =
      'assets/images/Menu/Levels/06.png';

  /// {@macro assets_generator.assets_images_menu_levels_07_png.preview}
  static const String assets_images_menu_levels_07_png =
      'assets/images/Menu/Levels/07.png';

  /// {@macro assets_generator.assets_images_menu_levels_08_png.preview}
  static const String assets_images_menu_levels_08_png =
      'assets/images/Menu/Levels/08.png';

  /// {@macro assets_generator.assets_images_menu_levels_09_png.preview}
  static const String assets_images_menu_levels_09_png =
      'assets/images/Menu/Levels/09.png';

  /// {@macro assets_generator.assets_images_menu_levels_10_png.preview}
  static const String assets_images_menu_levels_10_png =
      'assets/images/Menu/Levels/10.png';

  /// {@macro assets_generator.assets_images_menu_levels_11_png.preview}
  static const String assets_images_menu_levels_11_png =
      'assets/images/Menu/Levels/11.png';

  /// {@macro assets_generator.assets_images_menu_levels_12_png.preview}
  static const String assets_images_menu_levels_12_png =
      'assets/images/Menu/Levels/12.png';

  /// {@macro assets_generator.assets_images_menu_levels_13_png.preview}
  static const String assets_images_menu_levels_13_png =
      'assets/images/Menu/Levels/13.png';

  /// {@macro assets_generator.assets_images_menu_levels_14_png.preview}
  static const String assets_images_menu_levels_14_png =
      'assets/images/Menu/Levels/14.png';

  /// {@macro assets_generator.assets_images_menu_levels_15_png.preview}
  static const String assets_images_menu_levels_15_png =
      'assets/images/Menu/Levels/15.png';

  /// {@macro assets_generator.assets_images_menu_levels_16_png.preview}
  static const String assets_images_menu_levels_16_png =
      'assets/images/Menu/Levels/16.png';

  /// {@macro assets_generator.assets_images_menu_levels_17_png.preview}
  static const String assets_images_menu_levels_17_png =
      'assets/images/Menu/Levels/17.png';

  /// {@macro assets_generator.assets_images_menu_levels_18_png.preview}
  static const String assets_images_menu_levels_18_png =
      'assets/images/Menu/Levels/18.png';

  /// {@macro assets_generator.assets_images_menu_levels_19_png.preview}
  static const String assets_images_menu_levels_19_png =
      'assets/images/Menu/Levels/19.png';

  /// {@macro assets_generator.assets_images_menu_levels_20_png.preview}
  static const String assets_images_menu_levels_20_png =
      'assets/images/Menu/Levels/20.png';

  /// {@macro assets_generator.assets_images_menu_levels_21_png.preview}
  static const String assets_images_menu_levels_21_png =
      'assets/images/Menu/Levels/21.png';

  /// {@macro assets_generator.assets_images_menu_levels_22_png.preview}
  static const String assets_images_menu_levels_22_png =
      'assets/images/Menu/Levels/22.png';

  /// {@macro assets_generator.assets_images_menu_levels_23_png.preview}
  static const String assets_images_menu_levels_23_png =
      'assets/images/Menu/Levels/23.png';

  /// {@macro assets_generator.assets_images_menu_levels_24_png.preview}
  static const String assets_images_menu_levels_24_png =
      'assets/images/Menu/Levels/24.png';

  /// {@macro assets_generator.assets_images_menu_levels_25_png.preview}
  static const String assets_images_menu_levels_25_png =
      'assets/images/Menu/Levels/25.png';

  /// {@macro assets_generator.assets_images_menu_levels_26_png.preview}
  static const String assets_images_menu_levels_26_png =
      'assets/images/Menu/Levels/26.png';

  /// {@macro assets_generator.assets_images_menu_levels_27_png.preview}
  static const String assets_images_menu_levels_27_png =
      'assets/images/Menu/Levels/27.png';

  /// {@macro assets_generator.assets_images_menu_levels_28_png.preview}
  static const String assets_images_menu_levels_28_png =
      'assets/images/Menu/Levels/28.png';

  /// {@macro assets_generator.assets_images_menu_levels_29_png.preview}
  static const String assets_images_menu_levels_29_png =
      'assets/images/Menu/Levels/29.png';

  /// {@macro assets_generator.assets_images_menu_levels_30_png.preview}
  static const String assets_images_menu_levels_30_png =
      'assets/images/Menu/Levels/30.png';

  /// {@macro assets_generator.assets_images_menu_levels_31_png.preview}
  static const String assets_images_menu_levels_31_png =
      'assets/images/Menu/Levels/31.png';

  /// {@macro assets_generator.assets_images_menu_levels_32_png.preview}
  static const String assets_images_menu_levels_32_png =
      'assets/images/Menu/Levels/32.png';

  /// {@macro assets_generator.assets_images_menu_levels_33_png.preview}
  static const String assets_images_menu_levels_33_png =
      'assets/images/Menu/Levels/33.png';

  /// {@macro assets_generator.assets_images_menu_levels_34_png.preview}
  static const String assets_images_menu_levels_34_png =
      'assets/images/Menu/Levels/34.png';

  /// {@macro assets_generator.assets_images_menu_levels_35_png.preview}
  static const String assets_images_menu_levels_35_png =
      'assets/images/Menu/Levels/35.png';

  /// {@macro assets_generator.assets_images_menu_levels_36_png.preview}
  static const String assets_images_menu_levels_36_png =
      'assets/images/Menu/Levels/36.png';

  /// {@macro assets_generator.assets_images_menu_levels_37_png.preview}
  static const String assets_images_menu_levels_37_png =
      'assets/images/Menu/Levels/37.png';

  /// {@macro assets_generator.assets_images_menu_levels_38_png.preview}
  static const String assets_images_menu_levels_38_png =
      'assets/images/Menu/Levels/38.png';

  /// {@macro assets_generator.assets_images_menu_levels_39_png.preview}
  static const String assets_images_menu_levels_39_png =
      'assets/images/Menu/Levels/39.png';

  /// {@macro assets_generator.assets_images_menu_levels_40_png.preview}
  static const String assets_images_menu_levels_40_png =
      'assets/images/Menu/Levels/40.png';

  /// {@macro assets_generator.assets_images_menu_levels_41_png.preview}
  static const String assets_images_menu_levels_41_png =
      'assets/images/Menu/Levels/41.png';

  /// {@macro assets_generator.assets_images_menu_levels_42_png.preview}
  static const String assets_images_menu_levels_42_png =
      'assets/images/Menu/Levels/42.png';

  /// {@macro assets_generator.assets_images_menu_levels_43_png.preview}
  static const String assets_images_menu_levels_43_png =
      'assets/images/Menu/Levels/43.png';

  /// {@macro assets_generator.assets_images_menu_levels_44_png.preview}
  static const String assets_images_menu_levels_44_png =
      'assets/images/Menu/Levels/44.png';

  /// {@macro assets_generator.assets_images_menu_levels_45_png.preview}
  static const String assets_images_menu_levels_45_png =
      'assets/images/Menu/Levels/45.png';

  /// {@macro assets_generator.assets_images_menu_levels_46_png.preview}
  static const String assets_images_menu_levels_46_png =
      'assets/images/Menu/Levels/46.png';

  /// {@macro assets_generator.assets_images_menu_levels_47_png.preview}
  static const String assets_images_menu_levels_47_png =
      'assets/images/Menu/Levels/47.png';

  /// {@macro assets_generator.assets_images_menu_levels_48_png.preview}
  static const String assets_images_menu_levels_48_png =
      'assets/images/Menu/Levels/48.png';

  /// {@macro assets_generator.assets_images_menu_levels_49_png.preview}
  static const String assets_images_menu_levels_49_png =
      'assets/images/Menu/Levels/49.png';

  /// {@macro assets_generator.assets_images_menu_levels_50_png.preview}
  static const String assets_images_menu_levels_50_png =
      'assets/images/Menu/Levels/50.png';

  /// {@macro assets_generator.assets_images_menu_text_text_black_8x10_png.preview}
  static const String assets_images_menu_text_text_black_8x10_png =
      'assets/images/Menu/Text/Text Black 8x10.png';

  /// {@macro assets_generator.assets_images_menu_text_text_white_8x10_png.preview}
  static const String assets_images_menu_text_text_white_8x10_png =
      'assets/images/Menu/Text/Text White 8x10.png';

  /// {@macro assets_generator.assets_images_other_confetti_16x16_png.preview}
  static const String assets_images_other_confetti_16x16_png =
      'assets/images/Other/Confetti 16x16.png';

  /// {@macro assets_generator.assets_images_other_dust_particle_png.preview}
  static const String assets_images_other_dust_particle_png =
      'assets/images/Other/Dust Particle.png';

  /// {@macro assets_generator.assets_images_other_shadow_png.preview}
  static const String assets_images_other_shadow_png =
      'assets/images/Other/Shadow.png';

  /// {@macro assets_generator.assets_images_other_transition_png.preview}
  static const String assets_images_other_transition_png =
      'assets/images/Other/Transition.png';

  /// {@macro assets_generator.assets_images_terrain_terrain_16x16_png.preview}
  static const String assets_images_terrain_terrain_16x16_png =
      'assets/images/Terrain/Terrain 16x16.png';

  /// {@macro assets_generator.assets_images_traps_arrow_hit_18x18_png.preview}
  static const String assets_images_traps_arrow_hit_18x18_png =
      'assets/images/Traps/Arrow/Hit 18x18.png';

  /// {@macro assets_generator.assets_images_traps_arrow_idle_18x18_png.preview}
  static const String assets_images_traps_arrow_idle_18x18_png =
      'assets/images/Traps/Arrow/Idle 18x18.png';

  /// {@macro assets_generator.assets_images_traps_blocks_hitside_22x22_png.preview}
  static const String assets_images_traps_blocks_hitside_22x22_png =
      'assets/images/Traps/Blocks/HitSide 22x22.png';

  /// {@macro assets_generator.assets_images_traps_blocks_hittop_22x22_png.preview}
  static const String assets_images_traps_blocks_hittop_22x22_png =
      'assets/images/Traps/Blocks/HitTop 22x22.png';

  /// {@macro assets_generator.assets_images_traps_blocks_idle_png.preview}
  static const String assets_images_traps_blocks_idle_png =
      'assets/images/Traps/Blocks/Idle.png';

  /// {@macro assets_generator.assets_images_traps_blocks_part_1_22x22_png.preview}
  static const String assets_images_traps_blocks_part_1_22x22_png =
      'assets/images/Traps/Blocks/Part 1 22x22.png';

  /// {@macro assets_generator.assets_images_traps_blocks_part_2_22x22_png.preview}
  static const String assets_images_traps_blocks_part_2_22x22_png =
      'assets/images/Traps/Blocks/Part 2 22x22.png';

  /// {@macro assets_generator.assets_images_traps_falling_platforms_off_png.preview}
  static const String assets_images_traps_falling_platforms_off_png =
      'assets/images/Traps/Falling Platforms/Off.png';

  /// {@macro assets_generator.assets_images_traps_falling_platforms_on_32x10_png.preview}
  static const String assets_images_traps_falling_platforms_on_32x10_png =
      'assets/images/Traps/Falling Platforms/On 32x10.png';

  /// {@macro assets_generator.assets_images_traps_fan_off_png.preview}
  static const String assets_images_traps_fan_off_png =
      'assets/images/Traps/Fan/Off.png';

  /// {@macro assets_generator.assets_images_traps_fan_on_24x8_png.preview}
  static const String assets_images_traps_fan_on_24x8_png =
      'assets/images/Traps/Fan/On 24x8.png';

  /// {@macro assets_generator.assets_images_traps_fire_hit_16x32_png.preview}
  static const String assets_images_traps_fire_hit_16x32_png =
      'assets/images/Traps/Fire/Hit 16x32.png';

  /// {@macro assets_generator.assets_images_traps_fire_off_png.preview}
  static const String assets_images_traps_fire_off_png =
      'assets/images/Traps/Fire/Off.png';

  /// {@macro assets_generator.assets_images_traps_fire_on_16x32_png.preview}
  static const String assets_images_traps_fire_on_16x32_png =
      'assets/images/Traps/Fire/On 16x32.png';

  /// {@macro assets_generator.assets_images_traps_platforms_brown_off_png.preview}
  static const String assets_images_traps_platforms_brown_off_png =
      'assets/images/Traps/Platforms/Brown Off.png';

  /// {@macro assets_generator.assets_images_traps_platforms_brown_on_32x8_png.preview}
  static const String assets_images_traps_platforms_brown_on_32x8_png =
      'assets/images/Traps/Platforms/Brown On 32x8.png';

  /// {@macro assets_generator.assets_images_traps_platforms_chain_png.preview}
  static const String assets_images_traps_platforms_chain_png =
      'assets/images/Traps/Platforms/Chain.png';

  /// {@macro assets_generator.assets_images_traps_platforms_grey_off_png.preview}
  static const String assets_images_traps_platforms_grey_off_png =
      'assets/images/Traps/Platforms/Grey Off.png';

  /// {@macro assets_generator.assets_images_traps_platforms_grey_on_32x8_png.preview}
  static const String assets_images_traps_platforms_grey_on_32x8_png =
      'assets/images/Traps/Platforms/Grey On 32x8.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_blink_42x42_png.preview}
  static const String assets_images_traps_rock_head_blink_42x42_png =
      'assets/images/Traps/Rock Head/Blink 42x42.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_bottom_hit_42x42_png.preview}
  static const String assets_images_traps_rock_head_bottom_hit_42x42_png =
      'assets/images/Traps/Rock Head/Bottom Hit 42x42.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_idle_png.preview}
  static const String assets_images_traps_rock_head_idle_png =
      'assets/images/Traps/Rock Head/Idle.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_left_hit_42x42_png.preview}
  static const String assets_images_traps_rock_head_left_hit_42x42_png =
      'assets/images/Traps/Rock Head/Left Hit 42x42.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_right_hit_42x42_png.preview}
  static const String assets_images_traps_rock_head_right_hit_42x42_png =
      'assets/images/Traps/Rock Head/Right Hit 42x42.png';

  /// {@macro assets_generator.assets_images_traps_rock_head_top_hit_42x42_png.preview}
  static const String assets_images_traps_rock_head_top_hit_42x42_png =
      'assets/images/Traps/Rock Head/Top Hit 42x42.png';

  /// {@macro assets_generator.assets_images_traps_sand_mud_ice_ice_particle_png.preview}
  static const String assets_images_traps_sand_mud_ice_ice_particle_png =
      'assets/images/Traps/Sand Mud Ice/Ice Particle.png';

  /// {@macro assets_generator.assets_images_traps_sand_mud_ice_mud_particle_png.preview}
  static const String assets_images_traps_sand_mud_ice_mud_particle_png =
      'assets/images/Traps/Sand Mud Ice/Mud Particle.png';

  /// {@macro assets_generator.assets_images_traps_sand_mud_ice_sand_mud_ice_16x6_png.preview}
  static const String assets_images_traps_sand_mud_ice_sand_mud_ice_16x6_png =
      'assets/images/Traps/Sand Mud Ice/Sand Mud Ice 16x6.png';

  /// {@macro assets_generator.assets_images_traps_sand_mud_ice_sand_particle_png.preview}
  static const String assets_images_traps_sand_mud_ice_sand_particle_png =
      'assets/images/Traps/Sand Mud Ice/Sand Particle.png';

  /// {@macro assets_generator.assets_images_traps_saw_chain_png.preview}
  static const String assets_images_traps_saw_chain_png =
      'assets/images/Traps/Saw/Chain.png';

  /// {@macro assets_generator.assets_images_traps_saw_off_png.preview}
  static const String assets_images_traps_saw_off_png =
      'assets/images/Traps/Saw/Off.png';

  /// {@macro assets_generator.assets_images_traps_saw_on_38x38_png.preview}
  static const String assets_images_traps_saw_on_38x38_png =
      'assets/images/Traps/Saw/On 38x38.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_blink_54x52_png.preview}
  static const String assets_images_traps_spike_head_blink_54x52_png =
      'assets/images/Traps/Spike Head/Blink 54x52.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_bottom_hit_54x52_png.preview}
  static const String assets_images_traps_spike_head_bottom_hit_54x52_png =
      'assets/images/Traps/Spike Head/Bottom Hit 54x52.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_idle_png.preview}
  static const String assets_images_traps_spike_head_idle_png =
      'assets/images/Traps/Spike Head/Idle.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_left_hit_54x52_png.preview}
  static const String assets_images_traps_spike_head_left_hit_54x52_png =
      'assets/images/Traps/Spike Head/Left Hit 54x52.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_right_hit_54x52_png.preview}
  static const String assets_images_traps_spike_head_right_hit_54x52_png =
      'assets/images/Traps/Spike Head/Right Hit 54x52.png';

  /// {@macro assets_generator.assets_images_traps_spike_head_top_hit_54x52_png.preview}
  static const String assets_images_traps_spike_head_top_hit_54x52_png =
      'assets/images/Traps/Spike Head/Top Hit 54x52.png';

  /// {@macro assets_generator.assets_images_traps_spiked_ball_chain_png.preview}
  static const String assets_images_traps_spiked_ball_chain_png =
      'assets/images/Traps/Spiked Ball/Chain.png';

  /// {@macro assets_generator.assets_images_traps_spiked_ball_spiked_ball_png.preview}
  static const String assets_images_traps_spiked_ball_spiked_ball_png =
      'assets/images/Traps/Spiked Ball/Spiked Ball.png';

  /// {@macro assets_generator.assets_images_traps_spikes_idle_png.preview}
  static const String assets_images_traps_spikes_idle_png =
      'assets/images/Traps/Spikes/Idle.png';

  /// {@macro assets_generator.assets_images_traps_trampoline_idle_png.preview}
  static const String assets_images_traps_trampoline_idle_png =
      'assets/images/Traps/Trampoline/Idle.png';

  /// {@macro assets_generator.assets_images_traps_trampoline_jump_28x28_png.preview}
  static const String assets_images_traps_trampoline_jump_28x28_png =
      'assets/images/Traps/Trampoline/Jump 28x28.png';

  static const String assets_tiles_level_01_tmx = 'assets/tiles/level-01.tmx';

  static const String assets_tiles_level_02_tmx = 'assets/tiles/level-02.tmx';

  static const String assets_tiles_pixel_adventure_tiled_project =
      'assets/tiles/pixel_adventure.tiled-project';

  static const String assets_tiles_pixel_adventure_tiled_session =
      'assets/tiles/pixel_adventure.tiled-session';

  static const String assets_tiles_pixel_adventure_1_tsx =
      'assets/tiles/pixel_adventure_1.tsx';
}
